/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9lrlTsSETEz
 */
import { Link } from 'react-router-dom'
import { Input } from "@/components/landingpage/input"
import { Button } from "@/components/landingpage/button"
import Navbar from '../components/auth/Navbar'
import BenefitsLogo from '../assets/benefits.jpeg'
import FeatureLogo from '../assets/features.jpeg'
import { useNavigate  } from 'react-router-dom'
import { UserState } from "@/context/UserProvider"



export default function Component() {
  const navigate = useNavigate();
  const { user } = UserState();
  return (
    <div className="flex flex-col min-h-[100vh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
       <><Navbar/></>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 border-b">
          <div
            className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Book an appointment with the best doctors
              </h1>
              <p
                className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Consult with top doctors from around the world 24/7. Accessible and affordable healthcare at your
                fingertips.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2 mt-4">
            {user ? (
                // Render symptom input and search button if user is logged in
                <form className="flex space-x-2">
                  <Input className="max-w-lg flex-1" placeholder="Enter your symptoms" type="text" />
                  <Button className="bg-purple-600" type="submit" onClick={() => navigate("/doctorsview")}>Search</Button>
                </form>
              ) : (
                // Render login and signup buttons if user is not logged in
                <div className="flex space-x-2 justify-center items-center">
                  <Button className="bg-purple-600" onClick={() => navigate("/login")}>Log in</Button>
                  <Button className="bg-purple-600" onClick={() => navigate("/signup")}>Sign Up</Button>
                </div>
              )}
              </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-5 px-4 md:px-6 lg:gap-10">
            <img
              alt="Image"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="100"
              src="https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?size=626&ext=jpg&ga=GA1.1.735520172.1710806400&semt=sph"
              width="300" />
            <div className="flex flex-col items-start space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                  Find the right doctor for your needs
                </h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our platform connects you with the best qualified doctors. Whether you need a consultation or a second
                  opinion, we have the experts to help.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-purple-600 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  to="/doctorsview"
                  >
                  Book Appointment
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                  href="#">
                  Learn more
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-4 px-4 md:px-6 lg:gap-10">
            <img
              alt="Image"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="200"
                src={BenefitsLogo}
              width="200" />
            <div className="flex flex-col items-start space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">The Benefits of using DOCEASE</h2>
                <p
                  className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your team focus on shipping features instead of managing infrastructure with automated CI/CD,
                  built-in testing, and integrated collaboration.
                </p>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Convenience</h3>
                  <p>Consult with doctors from the comfort of your home. No need to travel or wait in line.</p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Quality Care</h3>
                  <p>Access to the best doctors from around the world. Expert advice at your fingertips.</p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">Affordable</h3>
                  <p>
                    High-quality healthcare at the cheapest prices. We believe everyone should have access to good
                    health.
                  </p>
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-bold">24/7 Access</h3>
                  <p>Consult with doctors at any time of the day or night. We are always here for you.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-12">
          <div className="container grid items-center gap-4 px-4 md:px-6 lg:gap-32">
            <img
              alt="Image"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="https://img.freepik.com/premium-vector/telemedicine-online-consultation-with-doctor-remote-medical-treatment-by-videocalling-device-medical-worker-video-chat-flat-vector-illustration_277904-23570.jpg"
              width="550" />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center gap-4 px-4 md:px-6 lg:gap-10">
            <div className="flex flex-col items-start space-y-4 mx-auto">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl ">
                  Experience the workflow the best frontend teams love.
                </h2>
                <p
                  className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your team focus on shipping features instead of managing infrastructure with automated CI/CD.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
               
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Sign up to get notified when we launch.
                  <Link className="underline underline-offset-2" href="#">
                    Terms & Conditions
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
